export type ChapterId = "opening" | "chapter-1" | "chapter-2" | "chapter-3";

export type Slide = {
  id: string;
  chapter: ChapterId;
  number: string;
  shortTitle: string;
  title: string;
  eyebrow: string;
  conclusion: string;
  reason: string;
  example: string;
  action: string;
  visual: string;
  note?: string;
  kind?: "opening" | "chapter" | "content" | "summary";
};

export const chapters = [
  { id: "opening" as const, label: "Opening", title: "X運用研修", range: "00" },
  { id: "chapter-1" as const, label: "Chapter 01", title: "専門性を育てる", range: "01-05" },
  { id: "chapter-2" as const, label: "Chapter 02", title: "見たくなる投稿", range: "06-10" },
  { id: "chapter-3" as const, label: "Chapter 03", title: "アルゴリズム", range: "11-21" },
];

export const slides: Slide[] = [
  {
    id: "opening",
    chapter: "opening",
    number: "00",
    shortTitle: "X運用研修",
    title: "X運用研修",
    eyebrow: "STORE ACCOUNT PLAYBOOK",
    conclusion: "店舗アカウントを育てるための運用ガイド",
    reason: "30-40分で、Xの考え方から明日の投稿までをつなげます。",
    example: "専門性・投稿づくり・会話設計の3章で学びます。",
    action: "スクロール、または矢印キーで始めましょう。",
    visual: "network",
    kind: "opening",
  },
  {
    id: "chapter-1",
    chapter: "chapter-1",
    number: "01",
    shortTitle: "専門性を育てる",
    title: "Xは「専門性」を育てるSNS",
    eyebrow: "CHAPTER 01",
    conclusion: "誰に、何の情報を届ける店なのか。まず軸を決める。",
    reason: "Xは投稿同士のつながりから、興味が近い人へ情報を広げます。",
    example: "本の投稿を重ねると、本好きのおすすめ欄へ届きやすくなります。",
    action: "自店を表す専門テーマを1つ言葉にしましょう。",
    visual: "chapterExpertise",
    kind: "chapter",
  },
  {
    id: "role-difference",
    chapter: "chapter-1",
    number: "02",
    shortTitle: "Instagramとの違い",
    title: "XはInstagramとは役割が違う",
    eyebrow: "1-1 / ROLE",
    conclusion: "Instagramは来店理由、Xは専門性と会話を育てる。",
    reason: "写真を蓄積して店の魅力を見せるInstagramに対し、Xは投稿と反応がリアルタイムに広がります。",
    example: "Instagramで売場の完成形を見せ、Xで選書理由や入荷の熱量を語る。",
    action: "同じ商品でも、Xでは『なぜ推すのか』を一言足しましょう。",
    visual: "platformCompare",
  },
  {
    id: "expertise-over-followers",
    chapter: "chapter-1",
    number: "03",
    shortTitle: "フォロワー数より専門性",
    title: "フォロワー数より、反応される専門性",
    eyebrow: "1-2 / GROWTH LOOP",
    conclusion: "人数より『興味が合う人からの反応』が成長をつくる。",
    reason: "おすすめ表示は、投稿への反応や閲覧傾向から『誰に役立つか』を学習します。",
    example: "本好きが保存・返信する投稿は、別の本好きにも届く可能性が高まります。",
    action: "フォロワー増加だけでなく、返信・いいね・引用の質を見ましょう。",
    visual: "growthLoop",
    note: "エンゲージメント＝いいね、返信、リポストなどの反応",
  },
  {
    id: "why-expertise",
    chapter: "chapter-1",
    number: "04",
    shortTitle: "専門性が重要な理由",
    title: "専門性は、おすすめへの入口になる",
    eyebrow: "1-3 / RECOMMENDATION",
    conclusion: "一貫した発信が『本好きに届けるべきアカウント』という手がかりになる。",
    reason: "Xはフォロー関係だけでなく、興味・反応・会話の近さから投稿を推薦します。",
    example: "本の情報→本好きへ表示→反応→影響力向上、という循環が生まれます。",
    action: "直近10投稿のうち、専門テーマが伝わる投稿を7本以上に。",
    visual: "recommendFlow",
  },
  {
    id: "quality-followers",
    chapter: "chapter-1",
    number: "05",
    shortTitle: "むやみに増やさない",
    title: "むやみにフォロワーを増やさない",
    eyebrow: "1-4 / AUDIENCE FIT",
    conclusion: "反応しない1,000人より、会話する100人を育てる。",
    reason: "興味の薄いフォロワーが増えると、投稿への反応率が下がりやすくなります。",
    example: "相互フォロー企画より、選書の工夫に返信してくれる読者との関係を優先。",
    action: "数字を追う施策より、専門テーマで会話が生まれる投稿を選びましょう。",
    visual: "followerCompare",
  },
  {
    id: "chapter-2",
    chapter: "chapter-2",
    number: "06",
    shortTitle: "見たくなる投稿",
    title: "見たくなる投稿を作る",
    eyebrow: "CHAPTER 02",
    conclusion: "写真で止め、言葉で熱量を伝え、継続で信頼をつくる。",
    reason: "店舗には、現場にいる人しか撮れない瞬間と語れない背景があります。",
    example: "入荷直後、売場づくり、スタッフの手元は店舗アカウント固有の素材です。",
    action: "今日の売場で『現場感が伝わる1枚』を探しましょう。",
    visual: "chapterPost",
    kind: "chapter",
  },
  {
    id: "photo-rhythm",
    chapter: "chapter-2",
    number: "07",
    shortTitle: "写真のメリハリ",
    title: "写真はメリハリを付ける",
    eyebrow: "2-1 / VISUAL RHYTHM",
    conclusion: "普段は寄り、ここぞで引く。スケール感に強弱をつける。",
    reason: "単品のおすすめが続くからこそ、大型フェアの全景が特別に見えます。",
    example: "日常：本1冊の寄り／告知：平台のまとまり／本番：売場全景。",
    action: "次の企画までに『寄り・中・引き』の3カットを撮影しましょう。",
    visual: "photoRhythm",
  },
  {
    id: "human-presence",
    chapter: "chapter-2",
    number: "08",
    shortTitle: "中の人が見える",
    title: "『中の人』が見える写真",
    eyebrow: "2-2 / HUMAN TOUCH",
    conclusion: "人の気配が、店舗への親近感と信頼をつくる。",
    reason: "商品だけより、誰がどんな思いで紹介しているかが見えると話しかけやすくなります。",
    example: "スタッフが本を手に持ち、背景に実際の売場を入れて撮影する。",
    action: "顔出し不要。手元、名札、選書コメントから始めましょう。",
    visual: "humanPhoto",
  },
  {
    id: "copy-heat",
    chapter: "chapter-2",
    number: "09",
    shortTitle: "投稿文の熱量",
    title: "投稿文には、事実より先に熱量を書く",
    eyebrow: "2-3 / COPYWRITING",
    conclusion: "『入荷しました』を『見てほしい理由』に変える。",
    reason: "事務連絡だけでは流されます。驚きやこだわりが、読む手を止めます。",
    example: "『全点揃いました』より『圧巻です…！全点コンプリート！』。",
    action: "事実＋感情＋店頭での体験、の3要素で書き換えましょう。",
    visual: "copyCompare",
  },
  {
    id: "not-only-viral",
    chapter: "chapter-2",
    number: "10",
    shortTitle: "バズだけを狙わない",
    title: "バズだけを狙わない",
    eyebrow: "2-4 / CONSISTENCY",
    conclusion: "伸びない日の投稿が、伸びる日の土台になる。",
    reason: "日々の小さな投稿で専門性と期待が蓄積されるから、大型企画が反響を得ます。",
    example: "日々の新刊・選書投稿→信頼→大型フェア投稿の大きな反響。",
    action: "単発の数字で判断せず、4週間単位で投稿と反応を振り返りましょう。",
    visual: "trustPyramid",
  },
  {
    id: "chapter-3",
    chapter: "chapter-3",
    number: "11",
    shortTitle: "アルゴリズム",
    title: "アルゴリズムを味方につける",
    eyebrow: "CHAPTER 03",
    conclusion: "小手先ではなく、届きやすい形で価値と会話を積み重ねる。",
    reason: "Xが見ているのは、投稿が誰に役立ち、どんな反応を生んだかです。",
    example: "時間・書き方・会話・第三者の声を組み合わせます。",
    action: "10の運用ポイントを、自店のルールに落とし込みましょう。",
    visual: "chapterAlgorithm",
    kind: "chapter",
  },
  {
    id: "posting-time",
    chapter: "chapter-3",
    number: "12",
    shortTitle: "投稿時間",
    title: "投稿時間は、相手の生活で決める",
    eyebrow: "3-1 / TIMING",
    conclusion: "ここぞの投稿は、ターゲットがXを見る時間に合わせる。",
    reason: "投稿直後に反応が集まると、その後の会話や表示が広がりやすくなります。",
    example: "通勤層は朝・夕、学生は放課後、休日イベントは前日夜と当日朝。",
    action: "3つの時間帯を2週間試し、反応の良い枠を見つけましょう。",
    visual: "timeTimeline",
  },
  {
    id: "hashtags",
    chapter: "chapter-3",
    number: "13",
    shortTitle: "ハッシュタグ",
    title: "ハッシュタグは、足すより絞る",
    eyebrow: "3-2 / SIGNAL",
    conclusion: "基本はなし。使うなら目的が明確な1個程度。",
    reason: "タグ・メンション・外部リンクが多い投稿は、本文の焦点がぼやけます。",
    example: "#本 #読書 #書店 #新刊…ではなく、企画固有のタグを1つ。",
    action: "そのタグから実際に投稿を探す人がいるか、付ける前に確認しましょう。",
    visual: "hashtagCompare",
  },
  {
    id: "url-in-reply",
    chapter: "chapter-3",
    number: "14",
    shortTitle: "URLはリプ欄",
    title: "URLはリプ欄で、情報をツリーにする",
    eyebrow: "3-3 / THREAD DESIGN",
    conclusion: "本投稿は魅力に集中し、詳細情報は最初のリプへ。",
    reason: "本文のリンクを減らすと読みやすく、リプ欄で有益な補足も積み上げられます。",
    example: "本投稿：フェアの魅力／リプ1：詳細URL／リプ2：対象商品。",
    action: "投稿前に、本投稿と最初のリプをセットで準備しましょう。",
    visual: "replyFlow",
  },
  {
    id: "self-repost",
    chapter: "chapter-3",
    number: "15",
    shortTitle: "セルフリポスト",
    title: "セルフリポストは2〜3割に抑える",
    eyebrow: "3-4 / CONTENT MIX",
    conclusion: "新しい価値を7〜8割、再掲を2〜3割。",
    reason: "リポストばかりでは新鮮な情報が減り、アカウントの価値が伝わりにくくなります。",
    example: "新規投稿8本に対し、見逃し防止のセルフリポストを2本。",
    action: "直近10件を数え、新規投稿が7件以上ある状態を保ちましょう。",
    visual: "contentDonut",
  },
  {
    id: "replies",
    chapter: "chapter-3",
    number: "16",
    shortTitle: "リプライ",
    title: "リプライは、運用の付録ではなく本編",
    eyebrow: "3-5 / CONVERSATION",
    conclusion: "反応には、いいねだけで終わらず会話を返す。",
    reason: "双方向のやり取りは、投稿が関心を生んだという強い手がかりになります。",
    example: "『読みました』に『どの場面が印象的でしたか？』と返して会話を広げる。",
    action: "投稿後30分は、返信と引用へのリアクション時間にしましょう。",
    visual: "chatConversation",
    note: "引用リポストは、自分のコメントを付ける新しい投稿として活用できます",
  },
  {
    id: "third-party",
    chapter: "chapter-3",
    number: "17",
    shortTitle: "第三者紹介",
    title: "自分の宣伝より、第三者の紹介が強い",
    eyebrow: "3-6 / SOCIAL PROOF",
    conclusion: "お客様の言葉が、店舗の魅力に客観的な説得力を加える。",
    reason: "第三者の推奨は、店自身の宣伝より信頼されやすい傾向があります。",
    example: "良い紹介をリポストし、引用で感謝と『伝えたかった点』を補足する。",
    action: "紹介を見つけたら、感謝→共感→補足の順で引用しましょう。",
    visual: "endorsementCompare",
    note: "サードパーティ・エンドースメント＝第三者の推奨による信頼効果",
  },
  {
    id: "negative-response",
    chapter: "chapter-3",
    number: "18",
    shortTitle: "ネガティブ対応",
    title: "ネガティブには、速さより冷静さ",
    eyebrow: "3-7 / RESPONSE POLICY",
    conclusion: "基本は反応しない。必要な案件だけ事実確認して対応する。",
    reason: "感情的な応酬は話題を広げ、店舗とお客様の双方に不利益を生みます。",
    example: "意見は記録してスルー。誤情報・安全・個人情報は社内ルールへ即時共有。",
    action: "返信前に『公開回答が必要か』を確認する判断フローを決めましょう。",
    visual: "negativeDecision",
  },
  {
    id: "keep-expertise",
    chapter: "chapter-3",
    number: "19",
    shortTitle: "専門性を崩さない",
    title: "本以外の投稿も、本との接点をつくる",
    eyebrow: "3-8 / BRAND FIT",
    conclusion: "話題を広げても、アカウントの軸は手放さない。",
    reason: "食品・文具・イベントも、書店らしい視点で語れば専門性の一部になります。",
    example: "『北海道野菜が登場』→『料理本と巡る北海道フェア』へ。",
    action: "投稿前に『本・読書・書店との接点』を一言加えましょう。",
    visual: "expertiseHub",
  },
  {
    id: "event-post",
    chapter: "chapter-3",
    number: "20",
    shortTitle: "イベント投稿",
    title: "イベントは、告知より体験を予告する",
    eyebrow: "3-9 / EVENT COPY",
    conclusion: "日時を伝えるだけでなく、店頭で何が起きるかを想像させる。",
    reason: "イベントは直接の来店動機。規模感と現場の熱量が行動を後押しします。",
    example: "『開催します』より『書店のど真ん中で、今週末開催します！』。",
    action: "場所の特徴＋体験＋日時＋参加方法の順で告知しましょう。",
    visual: "eventCompare",
  },
  {
    id: "summary",
    chapter: "chapter-3",
    number: "21",
    shortTitle: "まとめ",
    title: "専門性 × 継続 × 会話",
    eyebrow: "3-10 / SUMMARY",
    conclusion: "X運用は、毎日の小さな信頼づくり。",
    reason: "専門性が届け先をつくり、継続が期待を育て、会話が関係を深めます。",
    example: "売場の1枚→熱量ある一言→反応へ返信。この反復が影響力になります。",
    action: "明日、専門テーマに沿った1投稿と1つの会話を実行しましょう。",
    visual: "vennSummary",
    kind: "summary",
  },
];
